-- 011_provider_ranking.sql
-- Provider ranking used by stock-data-node providers/ranking.py.
-- The table was referenced but never created; seed MASSIVE as primary.

CREATE TABLE IF NOT EXISTS public.provider_ranking (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider    text NOT NULL,
    rank        integer NOT NULL,
    enabled     boolean DEFAULT true,
    config      jsonb DEFAULT '{}'::jsonb,
    created_at  timestamp with time zone DEFAULT now(),
    updated_at  timestamp with time zone DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS provider_ranking_provider_key
    ON public.provider_ranking (provider);

INSERT INTO public.provider_ranking (provider, rank, enabled) VALUES
    ('MASSIVE',  1, true),
    ('IBKR',     2, true),
    ('YFINANCE', 3, true)
ON CONFLICT (provider) DO UPDATE
    SET rank = EXCLUDED.rank,
        enabled = EXCLUDED.enabled,
        updated_at = now();
